
pipeline {

    agent any
   // triggers {
     // cron('*/4 * * * *')

//    }

    stages {
    //   stage ('GIT') {
     //       steps {
      //         echo "Getting Project from Git";
       //        git branch:"master", url: 'https://github.com/dhouha16/SpringBootTest-CI.git';
       //     }
        //}

       stage("Verification du version Maven") {
           steps {
                bat "mvn -version"
            }
        }
        stage("Supprimer le contenu du dossier target") {
                    steps {
                        script {
                            //this step attempts to clean the files and directories generated by Maven during its build
                            bat "mvn clean"
                        }
                    }
                }
        stage ("Creation du livrable"){
        			steps{
        				bat "mvn package -DskipTests=true"
        			}
//         			post {
//                     success {
//                        jacoco()
//                        junit '**/target/surefire-reports/TEST-*.xml'
//                     }
//                     }
        		}


        stage ("Lancement des Tests Unitaires"){
        		steps{
        			bat "mvn test"
        				}
        		}

//         stage('Jacoco Test '){
//         			steps{
//         				step([$class: 'JacocoPublisher',
//               					execPattern: 'target/*.exec',
//               					classPattern: 'target/classes',
//               					sourcePattern: 'src/main/java',
//               					exclusionPattern: 'src/test*'
//         				])
//         			}
//         		}

        stage("Analyse avec Sonar ") {
                	steps {
                   	bat "mvn sonar:sonar"
                	 }
               	}
    }
}